# Generated by Django 4.0.6 on 2022-08-01 05:37

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_career_options_alter_career_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidateinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField(default=-811021938)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('resumee', models.CharField(max_length=100)),
                ('coverletter', models.TextField()),
                ('jobtitle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='career.career')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
