# Generated by Django 4.0.6 on 2022-08-01 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_candidateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
