# Generated by Django 4.0.6 on 2022-08-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_candidateinfo_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='jobtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career'),
        ),
    ]
